version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0

jobs:
  build:
    docker:
      - image: cimg/node:16.13.0
    steps:
      - checkout
      - run:
          name: Install Backend Dependencies
          command: |
            cd backend
            npm install || true
      - run:
          name: Install Frontend Dependencies
          command: |
            cd frontend
            npm install || true
      - sonarcloud/scan

workflows:
  main:
    jobs:
      - build:
          context: sonarcloud
