version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0

jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.13.0
    steps:
      - checkout
      # Backend
      - run:
          name: Install Backend Dependencies
          command: cd backend && npm install
      # Frontend
      - run:
          name: Install Frontend Dependencies
          command: cd frontend && npm install
      # SonarCloud scan
      - sonarcloud/scan

workflows:
  main:
    jobs:
      - build-and-test:
          context: sonarcloud
